(function(){
 const storage='bobRealTradeJournalQueueV1';let queue=[],busy=false;
 try{queue=JSON.parse(localStorage.getItem(storage)||'[]');if(!Array.isArray(queue))queue=[];}catch(e){}
 const el=id=>document.getElementById(id),time=x=>new Date(x).toLocaleString('de-CH',{timeZone:'Europe/Zurich'});
 function status(text){if(el('realTradeStatus'))el('realTradeStatus').textContent=text;}
 async function request(action,payload){const r=await fetch('/api/real-trades/'+action,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload),signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error('Server antwortet mit '+r.status);return r.json();}
 async function flush(){if(busy||!queue.length)return;busy=true;try{while(queue.length){await request('write',queue[0]);queue.shift();localStorage.setItem(storage,JSON.stringify(queue));}status('Echter Trade: Protokoll mit Server synchronisiert.');}catch(e){status('Protokoll noch nicht synchronisiert: '+e.message+'. Lokale Einträge warten auf erneuten Versuch; Hintergrundaufzeichnung erst nach Serverbestätigung.');}finally{busy=false;}}
 function capture(trade,extra){if(!trade?.tradeId||trade.test)return;const data=JSON.parse(JSON.stringify({trade,timeframe:'15m',event:extra||null}));const last=queue.at(-1);if(JSON.stringify(last)===JSON.stringify(data))return;queue.push(data);try{localStorage.setItem(storage,JSON.stringify(queue));}catch(e){status('Lokale Sicherung fehlgeschlagen; Server-Synchronisierung wird versucht.');}flush();}
 function details(title,value){const d=document.createElement('details'),s=document.createElement('summary'),p=document.createElement('pre');s.textContent=title;p.textContent=JSON.stringify(value,null,2);p.style.cssText='white-space:pre-wrap;overflow-wrap:anywhere;font-size:12px';d.append(s,p);return d;}
 async function history(id,root,before){try{const r=await request('read',{tradeId:id,before});if(!before)root.replaceChildren();for(const e of r.events){root.append(details(time(e.at)+' · '+({'observation':'Markt und Empfehlungen','trade-opened':'Beginn der Aufzeichnung','trade-updated':'Trade-Plan aktualisiert','trade-closed-in-bob':'In Bob beendet','push-delivery':'Push-Versand','browser-event':'App-Ereignis','observation-error':'Aufzeichnungslücke'}[e.kind]||e.kind),e.payload));}if(r.more){const b=document.createElement('button');b.textContent='Ältere Einträge laden';b.onclick=()=>{b.remove();history(id,root,r.nextBefore);};root.append(b);}if(!r.events.length)root.textContent='Noch keine Einträge.';}catch(e){root.textContent='Verlauf nicht abrufbar: '+e.message;}}
 function executionForm(t){
 const form=document.createElement('form'),heading=document.createElement('p'),fields={};heading.textContent='Tatsächliche Ausführung in EUR erfassen (Gesamtverkauf; Teilverkäufe hier noch nicht abbildbar).';form.append(heading);
 for(const [key,label] of Object.entries({entryEUR:'Kaufkurs je Stück',exitEUR:'Verkaufskurs je Stück',quantity:'Stückzahl',feesEUR:'Gesamte Gebühren und Kosten in EUR'})){const l=document.createElement('label'),i=document.createElement('input');l.textContent=label;i.type='number';i.step='any';i.min=key==='feesEUR'?'0':'0.000001';i.required=true;i.value=t.snapshot.actualExecution?.[key]??({entryEUR:t.snapshot.product?.entry,quantity:t.snapshot.product?.quantity}[key]??'');l.append(i);form.append(l);fields[key]=i;}
 const b=document.createElement('button'),note=document.createElement('p');b.type='submit';b.textContent='Ausführung speichern';form.append(b,note);
 form.onsubmit=async e=>{e.preventDefault();b.disabled=true;try{const actualExecution=Object.fromEntries(Object.entries(fields).map(([k,v])=>[k,Number(v.value)]));await request('write',{trade:{...t.snapshot,actualExecution},timeframe:'15m'});note.textContent='Gespeichert · Ergebnis nach eingetragenen Kosten: '+((actualExecution.exitEUR-actualExecution.entryEUR)*actualExecution.quantity-actualExecution.feesEUR).toFixed(2)+' EUR. Angaben nicht mit DEGIRO abgeglichen.';}catch(err){note.textContent='Nicht gespeichert: '+err.message;}finally{b.disabled=false;}};return form;
 }
 async function load(){await flush();try{const r=await request('read',{}),root=el('realTradeList');root.replaceChildren();for(const t of r.trades){const d=document.createElement('details'),s=document.createElement('summary'),body=document.createElement('div');s.textContent=time(t.openedAt)+' · '+(t.snapshot.product?.isin||'Goldreferenz ohne Produktdaten')+' · '+t.snapshot.dir+' · '+(t.active?'aktiv':'in Bob beendet');d.append(s,details('Erfasster Trade und Produktwerte',t.snapshot));if(!t.active)d.append(executionForm(t));d.append(body);d.addEventListener('toggle',()=>{if(d.open&&!body.childNodes.length)history(t.id,body);});root.append(d);}if(!r.trades.length)root.textContent='Noch kein echter Trade protokolliert. Nach deinem Kauf den Trade unter „Mein Trade“ erfassen und aktivieren.';}catch(e){status('Echte Trades nicht abrufbar: '+e.message);}}
 window.BobRealTrades={capture,load};
 document.addEventListener('DOMContentLoaded',()=>{el('realTradeLoad')?.addEventListener('click',load);flush();});
 document.addEventListener('click',e=>{if(e.target.closest?.('[data-view="learning"]'))load();});
 window.addEventListener('online',flush);setInterval(flush,30000);
})();
