services:
  - type: web
    name: bob-private-scanner
    runtime: python
    plan: free
    region: frankfurt
    branch: main
    buildCommand: echo Bob
    startCommand: python server.py
    autoDeployTrigger: commit
    healthCheckPath: /
