const fs=require('fs'),vm=require('vm'),assert=require('assert');
const html=fs.readFileSync('Bob.html','utf8');
const script=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].find(m=>m[1].includes('const quotes={spot:null,future:null,estimate:null}'))[1];
const els=new Map(),el=id=>{if(!els.has(id))els.set(id,{textContent:'',className:'',style:{}});return els.get(id)};
let payload={spot:{price:4140,at:new Date().toISOString(),changePct:1.2,source:'fixture'},future:{price:4172.1,at:'2026-01-01T00:00:00Z',changePct:-.72,source:'fixture'}};
const context={window:{},document:{getElementById:el,visibilityState:'visible',addEventListener(){}},fetch:async()=>({ok:true,json:async()=>payload}),setTimeout:()=>0,clearTimeout(){},setInterval(){},AbortController,Date,Number};
vm.createContext(context);vm.runInContext(script,context);
setImmediate(async()=>{
 assert.equal(el('gold-spot-price').textContent,'—'); // Independent cards cannot override the analysis spot.
 context.window.BobGoldCards.spot({spots:{xaus:4140,spot_price_as_of:payload.spot.at,primary:'Gold-API'}});
 assert.equal(el('gold-spot-price').textContent,'4.140,00');
 assert.equal(el('gold-future-price').style.fontStyle,'italic');
 assert.equal(el('gold-future-change').textContent,'↓ −0,72 %');assert.equal(el('gold-future-state').textContent,'');
 context.window.BobGoldCards.spot({spots:{xaus:4141,spot_price_as_of:new Date(Date.now()+1000).toISOString(),primary:'Bob'}});
 assert.equal(el('gold-spot-change').textContent,'— %');assert.equal(el('gold-spot-basis').textContent,'Tagesänderung fehlt');
 context.window.BobGoldCards.spot({spots:{xaus:9999,spot_price_as_of:'2025-01-01T00:00:00Z'}});
 assert.equal(el('gold-spot-price').textContent,'4.141,00');
 payload.estimate={price:4180,at:new Date().toISOString(),kind:'calculated',changePct:-.5,changeLabel:'geschätzt zum Vortagesschluss'};
 await context.window.BobGoldCards.refresh();
 assert.equal(el('gold-spot-price').textContent,'4.141,00'); // New card refresh still cannot replace the analysis observation.
 assert.equal(el('gold-estimate-price').textContent,'≈ 4.180,00');
 assert.equal(el('gold-estimate-state').textContent,'Aktualisierung aktiv');
 assert.equal(el('gold-estimate-basis').textContent,'geschätzt zum Vortagesschluss');
 assert.equal(el('gold-future-price').textContent,'4.172,10');
 payload.estimate={price:null,note:'Schätzung pausiert'};
 await context.window.BobGoldCards.refresh();
 assert.equal(el('gold-estimate-price').textContent,'—');
 assert.equal(el('gold-estimate-state').textContent,'Aktualisierung pausiert');
 payload.estimate={price:4170,at:new Date(Date.now()-86400000).toISOString(),kind:'calculated',historical:true};
 await context.window.BobGoldCards.refresh();
 assert.equal(el('gold-estimate-price').textContent,'≈ 4.170,00');
 assert.equal(el('gold-estimate-state').textContent,'Aktualisierung pausiert');
 payload.estimate={price:4190,at:new Date().toISOString(),kind:'calculated'};
 await context.window.BobGoldCards.refresh();
 assert.equal(el('gold-estimate-price').textContent,'≈ 4.190,00');
 assert.equal(el('gold-estimate-state').textContent,'Aktualisierung aktiv');
 payload.cfd={price:4170.45,at:new Date(Date.now()-180000).toISOString(),kind:'cfd',changePct:-.04,note:'Echtzeit CFD · laut Investing.com'};
 await context.window.BobGoldCards.refresh();
 assert.equal(el('gold-cfd-price').textContent,'4.170,45');
 assert.equal(el('gold-cfd-change').className,'gold-change down');
 assert.equal(el('gold-cfd-state').textContent,'CFD-Kurs nicht aktuell');
 payload.cfd.at=new Date().toISOString();
 await context.window.BobGoldCards.refresh();
 assert.equal(el('gold-cfd-state').textContent,'Echtzeit CFD · laut Investing.com');
 payload.cfd={...payload.cfd,at:new Date(Date.now()+1000).toISOString(),changePct:.1};
 await context.window.BobGoldCards.refresh();
 assert.equal(el('gold-cfd-change').className,'gold-change up');
 context.window.BobGoldCards.spot({spots:{xaus:4180,spot_price_as_of:new Date(Date.now()+2000).toISOString(),dailyChange:{changePct:1,changeLabel:'zum Spot-Vortagesschluss (Investing.com)'}}});
 assert.equal(el('gold-spot-change').textContent,'↑ +1,00 %');assert.equal(el('gold-spot-change').className,'gold-change up');
 context.window.BobGoldCards.spot({spots:{xaus:4100,spot_price_as_of:new Date(Date.now()+3000).toISOString(),dailyChange:{changePct:-1}}});
 assert.equal(el('gold-spot-change').textContent,'↓ −1,00 %');assert.equal(el('gold-spot-change').className,'gold-change down');
 context.window.BobGoldCards.spot({spots:{xaus:4140,spot_price_as_of:new Date(Date.now()+4000).toISOString(),dailyChange:{changePct:0}}});
 assert.equal(el('gold-spot-change').textContent,'→ 0,00 %');assert.equal(el('gold-spot-change').className,'gold-change');
 console.log('Gold cards: formatting, directions, stale data, missing change and older response protection OK');
});
